apps/students/urls.py
from django.urls import path

from .views import (
    DownloadCSVViewdownloadcsv,
    StudentBulkUploadView,
    StudentCreateView,
    Studentdashboard,
    StudentDeleteView,
    StudentDetailView,
    StudentListView,
    StudentInActiveListView,
    StudentUpdateView,
    select_enquiry,
    CreateBooklLog,
    delete_book_log,
    delete_class_log,
    CreateClasslLog,
    CreateExamLog,
    delete_exam_log,
    delete_certificate_log,
    CreateCertificateLog,
    PublicView,
    generate_student_id_card,
    BreakDetailsCreateView,
    BreakDetailsUpdateView,
    BreakDetailsDeleteView,
    BreakDetailsInActiveListView,
    StudentInActiveListView,
    BreakDetailsDetails,
    add_followup,
    delete_followup,
    
    
)

urlpatterns = [
    path('generate_student_id_card/<int:student_id>/', generate_student_id_card, name='generate_student_id_card'),
    path("",Studentdashboard,name="dashboard"),
    path('select_enquiry/', select_enquiry, name='select_enquiry'),
    path("list", StudentListView.slist, name="student-list"),
    path("inactive", StudentInActiveListView.slist, name="student-inactive-list"),
    path("<int:pk>/", StudentDetailView.as_view(), name="student-detail"),
    path("create/<int:enquiry_id>/", StudentCreateView.as_view(), name="student-create"),
    path("<int:pk>/update/", StudentUpdateView.as_view(), name="student-update"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="student-delete"),
    path("upload/", StudentBulkUploadView.as_view(), name="student-upload"),
    path("download-csv/", DownloadCSVViewdownloadcsv.as_view(), name="download-csv"),
    path("<int:pk>/booklog/",CreateBooklLog.as_view(),name="booklog"),
    path("bookdel/<int:pk>/", delete_book_log, name="book-delete"),
    path("<int:pk>/classlog/",CreateClasslLog.as_view(),name="classlog"),
    path("classdel/<int:pk>/", delete_class_log, name="class-delete"),
    path("<int:pk>/examlog/",CreateExamLog.as_view(),name="examlog"),
    path("examdel/<int:pk>/", delete_exam_log, name="exam-delete"),
    path("<int:pk>/certificatelog/",CreateCertificateLog.as_view(),name="certificatelog"),
    path("certificatedel/<int:pk>/", delete_certificate_log, name="certificate-delete"),
    path("break_details/list",BreakDetailsInActiveListView.slist,name="break_details"),
    path("break_details/create",BreakDetailsCreateView.as_view(),name="break_details_create"),
    path("break_details/update/<int:pk>/",BreakDetailsUpdateView.as_view(),name="break_details_update"),
    path("break_details/delete/<int:pk>/",BreakDetailsDeleteView.as_view(),name="break_details_delete"),
    path("break_details/details/<int:pk>/",BreakDetailsDetails,name="break_details_details"),
    path("break_details/add_followup/<int:pk>/",add_followup,name="add_followup"),
    path("break_details/delet_followup/<int:pk>/<int:index>/",delete_followup,name="delete_followup"),
]

csc_app/urls.py
from apps.enquiry.views import StudentEnquiryFormCreateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path,re_path
from django.views.static import serve
from apps.students import views
from apps.corecode.views import logout_view,login_url
handler404 = 'apps.students.views.handler404'
urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('login/<str:username>/<str:password>/', login_url, name='login_url'),
    path('admin/', admin.site.urls , name='admin'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
    path("enquiry/",include("apps.enquiry.urls")),
    path('public/student/<int:pk>/', views.PublicView.as_view(), name='public_student_profile'),
    path('public/student/<int:pk>/attendance', views.attendance_test, name='public_student_profile_attendance'),
    path("revenue/", include("apps.revenue.urls")),
    path("course/", include("apps.course.urls")),
    path("batches/",include("apps.batch.urls")),
    path("attendance/",include("apps.attendancev2.urls")),
    path('logout/',logout_view, name='logout'),
    path('enquiryform',StudentEnquiryFormCreateView.as_view(),name='enquiryform')
] 

apps/students/models.py
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from datetime import datetime 
from django.db import models
from django.urls import reverse
from django.utils import timezone
from datetime import date,datetime
from apps.course.models import CourseModel
from apps.staffs.models import Staff
from apps.corecode.models import StudentClass , Book , Subject , Schemes
from apps.corecode.models import Time
from ..enquiry.models import *
from apps.corecode.models import User,Inventory

class Student(models.Model):
    username = models.CharField(max_length=20,blank=True)
    password = models.CharField(max_length=20,blank=True)
    GENDER_CHOICES = [("male", "Male"), ("female", "Female"),("others","others")]
    RELIGION_CHOICE = [('Hindu','Hindu'),('Christian','Christian'),('Muslim','Muslim'),("others","others")]
    COMMUNITY_CHOICE = [('OC','OC'),('BC','BC'),('MBC','MBC'),('ST/SC','ST/SC'),("others","others")]
    STUDENT_ROLE_CHOICES = [
        ("Employed", "Employed"),
        ("Unemployed", "Unemployed"),
        ("Housewife", "Housewife"),
        ("Businessman", "Businessman"),
        ("Student", "Student"),
        ("Others", "Others"),
    ]
    STATUS_CHOICES = [("active", "Active"), ("inactive", "Inactive")]
    if_enq = models.ForeignKey(Enquiry,on_delete=models.PROTECT,default=None,null=True) #enquiry relations
    current_status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="active"
    )
    scheme = models.ForeignKey(Schemes,on_delete=models.PROTECT,default=None,null=True)
    student_name = models.CharField("Student Name", max_length=255, blank=False, default="")
    enrol_no = models.IntegerField("Enrollment Number",default=0,null=False,unique=True)
    rel_name = models.CharField(
                default=None, max_length=255, verbose_name="Father/Husband Name"
            )
    rel_occupation = models.CharField("Father/Husband Occupation",max_length=255,default=None,null=False,blank=False)
    m_name = models.CharField(
                default="", max_length=255, verbose_name="Mother Name",null=True
            )
    date_of_birth = models.DateField(
                default=timezone.now, verbose_name="Date of Birth"
            )
    age = models.IntegerField("Age",default=0,blank=False)
    gender = models.CharField("Gender", max_length=10, choices=GENDER_CHOICES, default="male")
    
    religion = models.CharField("Religion",max_length=554,default="Hindu",choices=RELIGION_CHOICE)
    community = models.CharField("Community",max_length=524,default="OC", choices=COMMUNITY_CHOICE)
    occupation = models.CharField(
                choices=[
                    ("Employed", "Employed"),
                    ("Unemployed", "Unemployed"),
                    ("Housewife", "Housewife"),
                    ("Businessman", "Businessman"),
                    ("Student", "Student"),
                    ("Others", "Others"),
                ],
                default="Student",
                max_length=1024,
                verbose_name="Student Occupation",
            )
    student_company_name = models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="If Emloyed Company Name",
            )
    
    aadhar_no = models.BigIntegerField("Aadhar Number",null=True,default=None,blank=True)

    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    mobile_number = models.CharField("Mobile Number",
        validators=[mobile_num_regex], max_length=13, blank=True
    )
    alt_number = models.CharField("Alternate Number",
        validators=[mobile_num_regex], max_length=13, blank=True
    )
    email = models.EmailField("Email", blank=True, null=True,default="")
 
    #personal Details


    
    passport = models.ImageField("Photo",blank=False, upload_to="students/passports/")
    address = models.CharField("Address", max_length=255,default=None,blank=True)
    address1 = models.CharField("Address Line 2", max_length=255,default=None,blank=True,null=True)
    address2 = models.CharField("Address Line 3", max_length=255,default=None,blank=True,null=True)
    taluka = models.CharField("Taluk",max_length=255,default=None,blank=True,null=True)
    district = models.CharField("District",max_length=255,default=None,blank=True,null=True)
    pincode = models.IntegerField("Pincode", blank=True, default=None, null=True)

    #course
    date_of_admission = models.DateField(default=timezone.now)
    course = models.ForeignKey(CourseModel,on_delete=models.PROTECT)
    class_time = models.ManyToManyField(Time,verbose_name="Class Timing",blank=True)

     

    #fees

    total_fee = models.IntegerField("Total Fees",null=False,default=0)
    remark = models.CharField("Remark",max_length=500,default=None,blank=True)
    
    last_updated = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True,related_name='student_profile')
    
    
    class Meta:
        ordering = ["enrol_no"]

    def __str__(self):
        return f"{self.student_name}({self.enrol_no})"

    def get_absolute_url(self):
        return reverse("student-detail", kwargs={"pk": self.pk})
    


    def save(self, *args,from_save_update = True, **kwargs):
        if from_save_update:
            self.username = self.enrol_no
            self.password = self.formatted_date_of_birth()
            if not self.user:
                self.user = User.objects.create_user(username=self.enrol_no,password=self.formatted_date_of_birth(),is_staff=False)
            else:
                self.user.username = self.enrol_no
                self.user.set_password(self.formatted_date_of_birth())
                self.user.save()
            super().save(*args, **kwargs)
        elif from_save_update == False:
            self.user.delete()
            self.user = None
            super().save(*args, **kwargs)
    
    
    def delete(self, *args, **kwargs):
        # Delete the associated user before deleting the Staff instance
        self.save(from_save_update=False)
        super().delete(*args, **kwargs)
    
    def formatted_date_of_birth(self):
        # Get the date of birth
        dob = self.date_of_birth

        # Format the date as "ddmmyyyy"
        formatted_date = dob.strftime('%d%m%Y')

        return formatted_date
    
class Bookmodel(models.Model):
    student = models.ForeignKey(Student,on_delete=models.PROTECT)
    received_book = models.ForeignKey(Book , on_delete=models.CASCADE)
    received_date = models.DateField("Book received Date",default=timezone.now)
    handled_by = models.ForeignKey(Staff,verbose_name="Handled Staff",on_delete = models.DO_NOTHING)
    def get_absolute_url(self):
        return reverse("student-detail", kwargs={"pk": self.student.pk})
    remark = models.CharField("Remark",max_length=2046,blank=True,default=None)
    last_updated = models.DateTimeField(auto_now=True)
    
    def save(self,*args,**kwargs):
        
        if self.received_date < datetime.strptime("2025-01-01","%Y-%m-%d").date():
            super().save(*args, **kwargs)
        else:
            orders,total = Inventory().book_stock(self.received_book.id)
            print(orders,total)
            if total<=0:
                raise ValidationError(f'Stock for the book {self.received_book} is empty please add some stock')
            else:
                id = min(list(map(lambda x:x['id'],orders)))
                obj = Inventory.objects.get(id=id)
                obj.items[str(self.received_book.id)] -= 1
                obj.save()
            super().save(*args,**kwargs)
    
    def delete(self, *args, **kwargs):
        if self.received_date < datetime.strptime("2025-01-01","%Y-%m-%d").date():
            super().delete(*args, **kwargs)
        else:
            orders,total = Inventory().book_stock(self.received_book.id)
            print(orders,total)
            if total<=0:
                raise ValidationError(f'Stock for the book {self.book} is empty please add some stock')
            else:
                id = min(list(map(lambda x:x['id'],orders)))
                obj = Inventory.objects.get(id=id)
                obj.items[str(self.received_book.id)] += 1
                obj.save()
                super().delete(*args, **kwargs)
        
class Classmodel(models.Model):
    student = models.ForeignKey(Student,on_delete=models.PROTECT,blank=True)
    finised_subject = models.CharField("Finised Subject",max_length=255,default=None,blank=False)
    start_date = models.DateField("Started on")
    end_date = models.DateField("Ended on",null=True,blank=True)
    class_time = models.ForeignKey(Time,verbose_name="Class Timing",on_delete=models.DO_NOTHING,blank=True)
    faculty = models.ForeignKey(Staff,verbose_name="Handled Staff",on_delete = models.DO_NOTHING)
    remark = models.CharField("Remark",max_length=2046,blank=True,default=None)
    last_updated = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse("student-detail", kwargs={"pk": self.student.pk})

    
class Exammodel(models.Model):
    student = models.ForeignKey(Student,on_delete=models.PROTECT)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    exam_date = models.DateField("Exam date",default=timezone.now)
    contected_mode = models.CharField("Mode",choices=[("Online","Online"),("Offline","Offline")],max_length=255,blank=True,null=True,default=None)
    theory_mark =models.FloatField("Theory mark",blank=True,null=True,default=None)
    paratical_mark = models.FloatField("Paratical mark",blank=True,default=None)
    mark = models.FloatField("Total mark",blank=True)
    remark = models.CharField("Remark",max_length=2046,blank=True,default=None)
    last_updated = models.DateTimeField(auto_now=True)

apps/students/templates/students/ad_con.html
<!-- select_enquiry.html -->
{% extends 'base.html' %}

{% block title %}
  Select Enquiry
{% endblock title %}

{% block content %}
<div class="container mt-5">
  <h2>Select Enquiry</h2>
  <form method="post" action="">
    {% csrf_token %}
    
    <label for="enquiry">Select Enquiry:</label>
    <input type="text" name="enquiry" id="enquiry" class="form-control" list="enquiry-list"  autocomplete="off"/>
    <datalist id="enquiry-list">
      {% for enquiry in enquiries %}
        <option value="{{ enquiry.name }}({{enquiry.enquiry_no}}) {{ enquiry.auto_increment }} {{enquiry.mobile_number}}"></option>
      {% endfor %}
    </datalist>

    <button type="submit" id="changeit" class="btn btn-primary mt-3">Next</button>
  </form>
</div>
<script>
  document.getElementById('changeit').addEventListener('click', function() {
    var selectedOption = document.querySelector('#enquiry-list option[value="' + 
document.getElementById('enquiry').value + '"]');

    // Check if a valid option is selected
    if (selectedOption) {
      var inputText = 
document.getElementById('enquiry').value;
      var match = inputText.match(/\) (\d+)/);
      
      if (match) {
      var lastNumbers = match[1];
      
document.getElementById('enquiry').value = lastNumbers;//lastNumbers;
      } else {
      console.log("No numbers found at the end of the text");
      } 
      // Allow the form submission if a valid option is selected
      return true;
    } else {
      // Prevent the form submission if no valid option is selected
      event.preventDefault();
      alert('Please select a valid option from the list.');
      return false;
    }
    // Run the code when the input value changes
    
  }
  );
</script>
{% endblock content %}

apps/students/templates/students/breakdetails_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "BreakForm"?</p>
    <p>Student Provided in the Data will be remain inactive</p>
    <p>update the data to set _is_joined = yes to reactivate Student</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

apps/students/templates/students/student_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this student will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

apps/students/templates/students/student_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="{% url 'booklog' object.id %}"><input type="button" class="btn btn-sm btn-primary" value="Book"></a>
    <a href="{% url 'examlog' object.id %}"><input type="button" class="btn btn-sm btn-primary" value="Exam"></a>
    <a href="{% url 'certificatelog' object.id %}"><input type="button" class="btn btn-sm btn-primary" value="Certificate"></a>
    <a href="{% url 'generate_student_id_card' object.id %}" class="btn btn-tool">Print</a>
    <a href="{% url 'student-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'student-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-trash"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row mb-4">
      <div class="col-sm-4">
        <div class="row mb-2">

          {% if object.passport %}
            <img
              src="{{ object.passport.url }}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% else %}
            <img
              src="{% static 'dist/img/avatar.png' %}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% endif %}


          <div class="float-right">
            <h4>{{ object.student_name }} </h4>
            <h4>{{ object.enrol_no }} </h4>
          </div>
          
        </div>
        <h5><a href="{% url 'details_course' object.course.id%}">{{ object.course }}</a> </h5>
        <h5>{{ object.get_gender_display }} | {{ object.get_current_status_display }}</h5>
        <h5> {{object.scheme}}</h5>
        {% if object.if_enq.counsellor %}
        <h5>Followed By : <a href="{% url 'staff-detail' object.if_enq.counsellor.id%}">{{object.if_enq.counsellor}}</a></h5>
        {% endif %}

      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Username
            </label>
            <div class="col">
              {{ object.username }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Password
            </label>
            <div class="col">
              {{ object.password }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Date of Admission
            </label>
            <div class="col">
              {{ object.date_of_admission }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
               Mobile Number
            </label>
            <div class="col">
              {{ object.mobile_number}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Student View Link
            </label>
            <div class="col">
              <a href="{%  url 'public_student_profile'  object.id %}"><input type="button" class="btn btn-sm btn-primary" value="Link"></a>
              <a href="{% url 'generate_student_id_card' object.id %}"><input type="button" class="btn btn-sm btn-primary" value="ID card"></a>
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Class Timinig
            </label>
            <div class="col">
              <ul style="margin-left: -30px;">
              {% for time in object.class_time.all %}
                  <li>{{ time.time }}</li>
              {% endfor %}
              </ul>
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Address
            </label>
            <div class="col">
              {{ object.address }}<br>
              {{ object.address1 }}<br>
              {{ object.address2 }}
            </div>
          </div>

        </div>

      </div>
    </div>
    <div class="row">
      {% for due in dues %}
      {% if due.invoice.student.id == object.id%}
          <div class="col-md-6 mb-4">
              <div class="card">
                  <div class="card-header">
                      Invoice #{{ due.invoice.id }} for Student : {{due.invoice.student.student_name}}
                  </div>
                  <div class="card-body">
                      <h5 class="card-title">Amount: ${{ due.amount }}</h5>
                      <p class="card-text">Due Date: {{ due.due_date }}</p>
                      <p class="card-text">Status: {{ due.due_status }}</p>
                      <small class="text-muted">Created at: {{ due.created_at }}</small>
                      <div class="mt-3">
                          <!-- Extend Form -->
                          <a href="/finance/bill/?due={{due.id}}" class="m-2 btn btn-info">Pay now
                          </a>
                          <a href="{% url 'update_due' due.id %}" class="m-2 btn btn-info">Edit
                          </a>
                          <!-- Delete Form -->
                          <form class="d-inline-block" method="POST" action="{% url 'delete_due' due.id %}">
                              {% csrf_token %}
                              
                              <button type="submit" class="btn btn-danger mb-2">Delete</button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
          {% endif %}
      {% endfor %}
  </div>
    <h4>Book Issuesed Details</h4>
    {% if booklog %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>Date</th>
            <th>Recivied Book</th>
            <th>Handel By</th>
            <th>Remark</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for book in booklog %}
            <tr>
              <td>{{book.received_date}} </td>
              <td>{{book.received_book}}</td>
              <td>{{book.handled_by}}</td>
              <td>{{book.remark}}</td>
              <td><a href="{% url 'book-delete' book.id%}"><input type="button" class="btn btn-sm btn-primary" value="Delete"></a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no booklog history for {{object}}</p>
    {% endif %}


{% comment %} ---------------------------------------------------------------------------- {% endcomment %}
<!-- {{batches}} -->
 <div class="row m-2 my-4">
  <div class="col-4">
    <h4>Batch Enrolled </h4>
  </div>
  <div  class="col">
    <p class="text-info">click a batch to view the student attendance</p>  
  </div>
</div>

<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>S/N</th>
        <th>Batch Id</th>
        <th>Batch status</th>
        <th>Batch started On</th>
        <th>Batch course</th>
        <th>Batch Staff</th>
        <th>Batch Timing</th>
        <th>Total Student</th>
      </tr>
    </thead>
    <tbody>

      {% for batch in batches %}
        <tr class='clickable-row' data-href="{% url 'public_student_profile_attendance' object.id %}#{{batch.batch_id}}">
          <td>{{ forloop.counter}}</td>
          <td>{{ batch.batch_id}}</td>
          <td>{{ batch.batch_status}}</td>
          <td>{{ batch.batch_start_date}}</td>
          <td>{{ batch.batch_course}}</td>
          <td>{{ batch.batch_staff}}</td>
          <td>{{ batch.batch_timing}}</td>
          <td>{{ batch.total_student}}</td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
</div>
<h4>Class Details</h4>
{% if classlog %}
  <table id="studentBatchtable" class="table table-sm table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>Subject</th>
        <th>Class started on</th>
        <th>calss Ended on</th>
        <th>Class time</th>
        <th>Faculty</th>
        <th>Remark</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for class in classlog %}
        <tr>
          <td>{{class.finised_subject}} </td>
          <td>{{class.start_date}}</td>
          <td>{{class.end_date}}</td>
          <td>{{class.class_time.time}}</td>
          <td>{{class.faculty}}<td>
          {{class.remark}}
          <td><a href="{% url 'class-delete' class.id%}"><input type="button" class="btn btn-sm btn-primary" value="Delete"></a></td>
                
            </tr>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
    <p>There are no class history for {{object}}</p>
{% endif %}
    {% comment %} ---------------------------------------------------------------------------- {% endcomment %}

    <h4>Exam Details</h4>
    {% if examlog %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>Subject</th>
            <th>Contected on</th>
            <th>Contected Mode</th>
            <th>Theory mark</th>
            <th>Paratical mark</th>
            <th>
              Total mark</th>
              <th>Remark</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for exam in examlog %}
            <tr>
              <td>{{exam.subject}} </td>
              <td>{{exam.exam_date}}</td>
              <td>{{exam.contected_mode}}</td>
              <td>{{exam.theory_mark}}</td>
              <td>{{exam.paratical_mark}}</td>
              <td>{{exam.mark}}<td>
                {{exam.remark}}
                <td><a href="{% url 'exam-delete' exam.id%}"><input type="button" class="btn btn-sm btn-primary" value="Delete"></a></td>
                
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no Exam history for {{object}}</p>
    {% endif %}
    {% comment %} ---------------------------------------------------------------------------- {% endcomment %}

    <h4>Certificate Details</h4>
    {% if certilog %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>Course</th>
            <th>Date of Completion</th>
            <th>Certificate Number</th>
            <th>Certificate Date</th>
            <th>Certificate Issued Date</th>
            <th>
              Grade on Certificate</th>
              <th>Certificate Issued By</th>
              <th>Remark</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for log in certilog %}
            <tr>
              <td>{{log.course}} </td>
              <td>{{log.date_of_complete}}</td>
              <td>{{log.certificate_no}}</td>
              <td>{{log.certificate_date}}</td>
              <td>{{log.certificate_issued_date}}</td>
              <td>{{log.grade}}<td>
                {{log.issued_by}}
                
                <td>{{log.remark}}<td><a href="{% url 'certificate-delete' log.id%}"><input type="button" class="btn btn-sm btn-primary" value="Delete"></a></td>
              </td></tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no Certificate issued for {{object}}</p>
    {% endif %}
    
      
{% comment %} ---------------------------------------------------------------------------- {% endcomment %}
    <h4>Payment History</h4>
    {% if payments %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>Amount Payable</th>
            <th>Amount Paid</th>
            <th>balance</th>
          </tr>
        </thead>
        <tbody>
          {% for payment in payments %}
            <tr class='clickable-row' data-href="{% url 'invoice-detail' payment.id %}">
              <td>{{payment.total_amount_payable}}</td>
              <td>{{payment.total_amount_paid}}</td>
              <td>{{payment.balance}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no payment history for {{object}}</p>
    {% endif %}

    <script>
      $('#studentBatchtable').DataTable({
      });
    </script>


{% endblock content %}